In [1]:
import torch

In [2]:
abst = torch.tensor([15,  8,  7,  3,  7,  6, 14, 23, 14, 15,  8,  8,  5,  4, 12, 17,  2,  3,
         7, 29, 13, 14,  6, 26])

node = torch.tensor([15,  8,  7,  3,  7,  6, 14, 23, 14, 15,  8,  8,  5,  4, 12, 17,  2,  3,
         7, 29, 13, 14,  6, 26])

ind = torch.tensor([ 0,  1,  2,  3,  2,  5,  6,  7,  6,  0,  1,  1, 12, 13, 14, 15, 16,  3,
         2, 19, 20,  6,  5, 23])

In [20]:
def find_indices_tensor_x_graph(abst_tensor, nodes_device):
        flat_abst_tensor = abst_tensor.view(-1)
        indices = find_indices_tensor(flat_abst_tensor, nodes_device)
        return indices.view(abst_tensor.shape)

def find_indices_tensor(abst_tensor, nodes_device):
    # nodes_deviceの各値の最初のインデックスをマッピングする辞書を作成
    index_map = {}
    for index, value in enumerate(nodes_device.tolist()):
        if value not in index_map:
            index_map[value] = index

    # abst_tensorの各要素に対して、マッピングされたインデックスを見つける
    result_indices = [index_map[val] for val in abst_tensor.tolist()]

    # 結果をテンソルとして返す
    return torch.tensor(result_indices, device=nodes_device.device)
def find_indices(abst_list, nodes_device):
    indices = []
    nodes_numpy = nodes_device.to('cpu').numpy()
    nodes_to_idx = make_node_idx(nodes_numpy)
    #nodes_to_idx = {node: idx for idx, node in enumerate(nodes_numpy)} # ここのせいで、最終的に抜き出しのindexが-1になっている注意
    #nodes_set = set(nodes_numpy)
    indices = [nodes_to_idx[abst] for abst in abst_list]
    return indices

def make_node_idx(nodes_numpy):
    ret_dict = {}
    for idx, node in enumerate(nodes_numpy):
        if node not in ret_dict:
            ret_dict[node] = idx
    return ret_dict

In [23]:
print(f"abst{abst}")
print(f"node:{node}")
print(find_indices_tensor_x_graph(abst, node))
print(torch.tensor(find_indices(abst.tolist(), node)))
print(find_indices_tensor_x_graph(abst, node)==torch.tensor(find_indices(abst.tolist(), node)))

print(f"ans:{ind}")

absttensor([15,  8,  7,  3,  7,  6, 14, 23, 14, 15,  8,  8,  5,  4, 12, 17,  2,  3,
         7, 29, 13, 14,  6, 26])
node:tensor([15,  8,  7,  3,  7,  6, 14, 23, 14, 15,  8,  8,  5,  4, 12, 17,  2,  3,
         7, 29, 13, 14,  6, 26])
tensor([ 0,  1,  2,  3,  2,  5,  6,  7,  6,  0,  1,  1, 12, 13, 14, 15, 16,  3,
         2, 19, 20,  6,  5, 23])
tensor([ 0,  1,  2,  3,  2,  5,  6,  7,  6,  0,  1,  1, 12, 13, 14, 15, 16,  3,
         2, 19, 20,  6,  5, 23])
tensor([True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True])
ans:tensor([ 0,  1,  2,  3,  2,  5,  6,  7,  6,  0,  1,  1, 12, 13, 14, 15, 16,  3,
         2, 19, 20,  6,  5, 23])


In [7]:
print(ind)

tensor([ 0,  1,  2,  3,  2,  5,  6,  7,  6,  0,  1,  1, 12, 13, 14, 15, 16,  3,
         2, 19, 20,  6,  5, 23])
